#!/usr/bin/env python3
"""
scripts/new_questions_b1.py — 10 New MEXT Part B Questions (DRILL-B-91 to 100).
Strictly <= 200 lines invariant.
"""

QUESTIONS_B1 = [
    {
        "id": "DRILL-B-91",
        "section": "B",
        "level": "JLPT N3/N2",
        "category": "Compound Verbs (複合動詞)",
        "question": "提出する 前に、レポートの 誤字を もう一度（ ）。",
        "options": {"A": "見直した", "B": "見送った", "C": "見落とした", "D": "見つめた"},
        "answer": "A",
        "explanation": "「見直す」(みなおす)は再度確認・点検する意。「見落とす」は看過する。",
    },
    {
        "id": "DRILL-B-92",
        "section": "B",
        "level": "JLPT N3/N2",
        "category": "Compound Verbs (複合動詞)",
        "question": "図書館で 借りた 小説を 二日間で すべて（ ）しまった。",
        "options": {"A": "読み終えて", "B": "読み直して", "C": "読み飛ばして", "D": "読み返して"},
        "answer": "A",
        "explanation": "動詞ます形語幹＋「終える」で動作の完結を表す。",
    },
    {
        "id": "DRILL-B-93",
        "section": "B",
        "level": "JLPT N3/N2",
        "category": "Compound Verbs (複合動詞)",
        "question": "路地から 急に 子どもが 道路へ（ ）きて 驚いた。",
        "options": {"A": "飛び出して", "B": "飛び降りて", "C": "飛び越えて", "D": "飛び立って"},
        "answer": "A",
        "explanation": "「飛び出す」は突然中から外・前へ勢いよく出ること。",
    },
    {
        "id": "DRILL-B-94",
        "section": "B",
        "level": "JLPT N3/N2",
        "category": "Compound Verbs (複合動詞)",
        "question": "先輩から 頼まれた 面倒な 仕事を 喜んで（ ）。",
        "options": {"A": "引き受けた", "B": "引き止めた", "C": "引き返した", "D": "引き分けた"},
        "answer": "A",
        "explanation": "「引き受ける」は任務や責任を自分の役目として受託すること。",
    },
    {
        "id": "DRILL-B-95",
        "section": "B",
        "level": "JLPT N3/N2",
        "category": "Compound Verbs (複合動詞)",
        "question": "帰宅の 途中で 書店に（ ）、新しい 単語帳を 買った。",
        "options": {"A": "立ち寄って", "B": "立ち止まって", "C": "立ち上がって", "D": "立ち去って"},
        "answer": "A",
        "explanation": "「立ち寄る」は目的地へ行く途中でついでによること。",
    },
    {
        "id": "DRILL-B-96",
        "section": "B",
        "level": "JLPT N3/N2",
        "category": "Transitivity & State (自他動詞)",
        "question": "来週の 出張の スケジュールが やっと（ ）。",
        "options": {"A": "決まりました", "B": "決めました", "C": "定めました", "D": "選びました"},
        "answer": "A",
        "explanation": "スケジュール(主語)＋「決まる」(自動詞)。「決める」は他動詞。",
    },
    {
        "id": "DRILL-B-97",
        "section": "B",
        "level": "JLPT N3/N2",
        "category": "Transitivity & State (自他動詞)",
        "question": "風で キャンプファイヤーの 火が（ ）しまった。",
        "options": {"A": "消えて", "B": "消して", "C": "落として", "D": "失って"},
        "answer": "A",
        "explanation": "火(が)＋「消える」(自動詞)。「消す」は他動詞(を)。",
    },
    {
        "id": "DRILL-B-98",
        "section": "B",
        "level": "JLPT N3/N2",
        "category": "Transitivity & State (自他動詞)",
        "question": "注文した パソコンが 明日の 朝 実家に（ ）予定です。",
        "options": {"A": "届く", "B": "届ける", "C": "配る", "D": "送る"},
        "answer": "A",
        "explanation": "パソコンが(主語)実家に「届く」(自動詞)。「届ける」は配達する他動詞。",
    },
    {
        "id": "DRILL-B-99",
        "section": "B",
        "level": "JLPT N3/N2",
        "category": "Keigo (敬語)",
        "question": "社長は 先ほど お客さまと 一緒に お帰りに（ ）ました。",
        "options": {"A": "なり", "B": "いたし", "C": "申し上げ", "D": "いただき"},
        "answer": "A",
        "explanation": "「お〜になる」は相手の行為を高める尊敬語表現。",
    },
    {
        "id": "DRILL-B-100",
        "section": "B",
        "level": "JLPT N3/N2",
        "category": "Keigo (敬語)",
        "question": "確認の 上、午後 改めて こちらから お電話（ ）ます。",
        "options": {"A": "さしあげ", "B": "くださり", "C": "いただき", "D": "なされ"},
        "answer": "A",
        "explanation": "「お電話さしあげる」は相手に対して電話をかける謙譲表現。",
    },
]
