#!/usr/bin/env python3
"""
scripts/new_questions_a2.py — 15 New MEXT Part A Questions (DRILL-A-141 to 155).
Strictly <= 200 lines invariant.
"""

QUESTIONS_A2 = [
    {
        "id": "DRILL-A-141",
        "section": "A",
        "level": "JLPT N4/N5",
        "category": "Kanji Writing (Grafia)",
        "question": "庭に きれいな 花の 木を 【うえ】ました。",
        "options": {"A": "植え", "B": "直え", "C": "置え", "D": "増え"},
        "answer": "A",
        "explanation": "「うえる」は「植える」。「直す」「置く」「増える」との判別。",
    },
    {
        "id": "DRILL-A-142",
        "section": "A",
        "level": "JLPT N4/N5",
        "category": "Grammar Particles",
        "question": "彼は 毎日 走っている（ ）、全然 体重が 減りません。",
        "options": {"A": "のに", "B": "ので", "C": "なら", "D": "から"},
        "answer": "A",
        "explanation": "逆接・不満・意外を表す「〜のに」。予想と反対の結果になる用法。",
    },
    {
        "id": "DRILL-A-143",
        "section": "A",
        "level": "JLPT N4/N5",
        "category": "Conditionals (条件形)",
        "question": "窓を 開けた（ ）、涼しい 風が 入ってきた。",
        "options": {"A": "ら", "B": "ば", "C": "なら", "D": "と"},
        "answer": "A",
        "explanation": "〜たら「〜したところ(発見・契機)」。過去の発見には「〜たら」を用いる。",
    },
    {
        "id": "DRILL-A-144",
        "section": "A",
        "level": "JLPT N4/N5",
        "category": "Grammar Particles",
        "question": "大雪が 降った（ ）、電車が 止まって しまいました。",
        "options": {"A": "ために", "B": "ように", "C": "とおりに", "D": "そうに"},
        "answer": "A",
        "explanation": "原因・理由を表す「〜ために」。客観的な因果関係を示す表現。",
    },
    {
        "id": "DRILL-A-145",
        "section": "A",
        "level": "JLPT N4/N5",
        "category": "Grammar Particles",
        "question": "日本語の 新聞が 読める（ ）に なりたいです。",
        "options": {"A": "よう", "B": "そう", "C": "ため", "D": "こと"},
        "answer": "A",
        "explanation": "可能動詞＋「〜ようになる」で能力や状態の変化・到達を表す。",
    },
    {
        "id": "DRILL-A-146",
        "section": "A",
        "level": "JLPT N4/N5",
        "category": "Grammar Particles",
        "question": "来週 試験が ある（ ）どうか、先生に 聞いて みます。",
        "options": {"A": "か", "B": "が", "C": "と", "D": "の"},
        "answer": "A",
        "explanation": "「〜かどうか」の埋め込み疑問文形式。普通形＋かどうか。",
    },
    {
        "id": "DRILL-A-147",
        "section": "A",
        "level": "JLPT N4/N5",
        "category": "Grammar (〜やすい / 〜にくい)",
        "question": "この 靴は とても 軽くて（ ）やすいです。",
        "options": {"A": "歩き", "B": "歩く", "C": "歩いて", "D": "歩いた"},
        "answer": "A",
        "explanation": "動詞ます形語幹＋「〜やすい」で容易さ・性質を表す。",
    },
    {
        "id": "DRILL-A-148",
        "section": "A",
        "level": "JLPT N4/N5",
        "category": "Giving and Receiving (授受動詞)",
        "question": "先生に 日本の 文化に ついての 本を（ ）ました。",
        "options": {"A": "いただき", "B": "くれ", "C": "あげ", "D": "やり"},
        "answer": "A",
        "explanation": "目上の人から物をもらう謙譲表現「いただく」。",
    },
    {
        "id": "DRILL-A-149",
        "section": "A",
        "level": "JLPT N4/N5",
        "category": "Grammar (〜てある vs 〜ている)",
        "question": "誰も いない 部屋の 電気が ついて（ ）ます。",
        "options": {"A": "い", "B": "あり", "C": "おき", "D": "み"},
        "answer": "A",
        "explanation": "自動詞「つく」＋「〜ている」で結果状態を表す。",
    },
    {
        "id": "DRILL-A-150",
        "section": "A",
        "level": "JLPT N4/N5",
        "category": "Grammar (〜てある vs 〜ている)",
        "question": "机の 上に 明日の 資料が 置いて（ ）ます。",
        "options": {"A": "あり", "B": "い", "C": "しまい", "D": "み"},
        "answer": "A",
        "explanation": "他動詞「置く」＋「〜てある」で誰かが意図して準備した結果状態を表す。",
    },
    {
        "id": "DRILL-A-151",
        "section": "A",
        "level": "JLPT N4/N5",
        "category": "Transitive vs Intransitive",
        "question": "強い 風が 吹いて、窓が 急に（ ）。",
        "options": {"A": "閉まりました", "B": "閉めました", "C": "開けました", "D": "消しました"},
        "answer": "A",
        "explanation": "窓(主語)＋「閉まる」(自動詞)。「閉める」は他動詞。",
    },
    {
        "id": "DRILL-A-152",
        "section": "A",
        "level": "JLPT N4/N5",
        "category": "Vocabulary in Context",
        "question": "汚れた 服を 洗濯機に 入れて きれいに（ ）。",
        "options": {"A": "洗いました", "B": "拭きました", "C": "磨きました", "D": "干しました"},
        "answer": "A",
        "explanation": "洗濯機で服を「洗う」。「拭く」はタオル等、「磨く」は歯や靴。",
    },
    {
        "id": "DRILL-A-153",
        "section": "A",
        "level": "JLPT N4/N5",
        "category": "Transitive vs Intransitive",
        "question": "歩いて いる ときに、ポケットから 鍵を（ ）しまった。",
        "options": {"A": "落として", "B": "落ちて", "C": "下りて", "D": "下げて"},
        "answer": "A",
        "explanation": "鍵(を)＋「落とす」(他動詞)。「落ちる」は自動詞(が)。",
    },
    {
        "id": "DRILL-A-154",
        "section": "A",
        "level": "JLPT N4/N5",
        "category": "Vocabulary in Context",
        "question": "雨が やんで、暗かった 空が だんだん（ ）なってきた。",
        "options": {"A": "明るく", "B": "暗く", "C": "重く", "D": "寒く"},
        "answer": "A",
        "explanation": "雨がやんで空が「明るく」なる。形容詞連用形＋なる。",
    },
    {
        "id": "DRILL-A-155",
        "section": "A",
        "level": "JLPT N4/N5",
        "category": "Kanji Reading (Fonetica - 熟字訓)",
        "question": "【昨日】は 一日中 家で 試験の 勉強を しました。",
        "options": {"A": "きのう", "B": "さくじつ", "C": "きょう", "D": "あした"},
        "answer": "A",
        "explanation": "「昨日」の日常会話訓読み熟字訓は「きのう」。",
    },
]
