#!/usr/bin/env python3
"""
scripts/new_questions_a1.py — 15 New MEXT Part A Questions (DRILL-A-126 to 140).
Strictly <= 200 lines invariant.
"""

QUESTIONS_A1 = [
    {
        "id": "DRILL-A-126",
        "section": "A",
        "level": "JLPT N4/N5",
        "category": "Kanji Reading (Fonetica)",
        "question": "駅の 前で 【案内】の パンフレットを もらいました。",
        "options": {"A": "あんない", "B": "あない", "C": "あんないち", "D": "おくない"},
        "answer": "A",
        "explanation": "「案内」は「あんない」。案(あん)＋内(ない)。",
    },
    {
        "id": "DRILL-A-127",
        "section": "A",
        "level": "JLPT N4/N5",
        "category": "Kanji Reading (Fonetica)",
        "question": "旅行の 【準備】は もう すべて 終わりましたか。",
        "options": {"A": "じゅんび", "B": "ずんび", "C": "じゅんひ", "D": "じゅび"},
        "answer": "A",
        "explanation": "「準備」は「じゅんび」。備は「び」(濁音)。",
    },
    {
        "id": "DRILL-A-128",
        "section": "A",
        "level": "JLPT N4/N5",
        "category": "Kanji Reading (Fonetica)",
        "question": "友達と 三時に 会う 【約束】を しました。",
        "options": {"A": "やくそく", "B": "やくぞく", "C": "わくそく", "D": "やっそく"},
        "answer": "A",
        "explanation": "「約束」は「やくそく」。束は清音の「そく」。",
    },
    {
        "id": "DRILL-A-129",
        "section": "A",
        "level": "JLPT N4/N5",
        "category": "Kanji Reading (Fonetica)",
        "question": "次の 【急行】 電車に 乗ると 早く 着きます。",
        "options": {"A": "きゅうこう", "B": "きゅこう", "C": "きゅうぎょう", "D": "きゅぎょう"},
        "answer": "A",
        "explanation": "「急行」は「きゅうこう」。長音の「きゅう」。",
    },
    {
        "id": "DRILL-A-130",
        "section": "A",
        "level": "JLPT N4/N5",
        "category": "Kanji Reading (Fonetica)",
        "question": "バスは 定刻通りに バス停を 【出発】しました。",
        "options": {"A": "しゅっぱつ", "B": "しゅつはつ", "C": "しゅっばつ", "D": "しゅうはつ"},
        "answer": "A",
        "explanation": "「出発」は促音化して「しゅっぱつ」。",
    },
    {
        "id": "DRILL-A-131",
        "section": "A",
        "level": "JLPT N4/N5",
        "category": "Kanji Reading (Fonetica)",
        "question": "車が たくさん 通るので 【注意】して ください。",
        "options": {"A": "ちゅうい", "B": "じゅうい", "C": "ちゅい", "D": "ちゅうき"},
        "answer": "A",
        "explanation": "「注意」は「ちゅうい」。注(ちゅう)＋意(い)。",
    },
    {
        "id": "DRILL-A-132",
        "section": "A",
        "level": "JLPT N4/N5",
        "category": "Kanji Reading (Fonetica)",
        "question": "明日は 少し 【都合】が 悪いので 行けません。",
        "options": {"A": "つごう", "B": "とごう", "C": "つあい", "D": "ずごう"},
        "answer": "A",
        "explanation": "「都合」は「つごう」。合は連濁して「ごう」。",
    },
    {
        "id": "DRILL-A-133",
        "section": "A",
        "level": "JLPT N4/N5",
        "category": "Kanji Reading (Fonetica)",
        "question": "ホテルの 【受付】で 部屋の 鍵を もらいました。",
        "options": {"A": "うけつけ", "B": "うけづけ", "C": "うけつき", "D": "うけがき"},
        "answer": "A",
        "explanation": "「受付」は「うけつけ」。受(うけ)＋付(つけ)。",
    },
    {
        "id": "DRILL-A-134",
        "section": "A",
        "level": "JLPT N4/N5",
        "category": "Kanji Reading (Fonetica)",
        "question": "山の 上から 見た 海の 【景色】は とても 美しかった。",
        "options": {"A": "けしき", "B": "けいしょく", "C": "げしき", "D": "けいしき"},
        "answer": "A",
        "explanation": "「景色」は「けしき」。色を「しき」と読む語。",
    },
    {
        "id": "DRILL-A-135",
        "section": "A",
        "level": "JLPT N4/N5",
        "category": "Kanji Reading (Fonetica)",
        "question": "海外で 働いた 【経験】は 役に立ちます。",
        "options": {"A": "けいけん", "B": "げいけん", "C": "けいかん", "D": "けんけい"},
        "answer": "A",
        "explanation": "「経験」は「けいけん」。経(けい)＋験(けん)。",
    },
    {
        "id": "DRILL-A-136",
        "section": "A",
        "level": "JLPT N4/N5",
        "category": "Kanji Writing (Grafia)",
        "question": "休みの 日には 公園に 人が たくさん 【あつまり】ます。",
        "options": {"A": "集まり", "B": "拾まり", "C": "住まり", "D": "進まり"},
        "answer": "A",
        "explanation": "「あつまる」は「集まる」。「拾」はひろう、「住」はすむ。",
    },
    {
        "id": "DRILL-A-137",
        "section": "A",
        "level": "JLPT N4/N5",
        "category": "Kanji Writing (Grafia)",
        "question": "母に 誕生日 プレゼントを 【おくり】ました。",
        "options": {"A": "送り", "B": "返し", "C": "届き", "D": "通り"},
        "answer": "A",
        "explanation": "「おくる」は「送る」。「返」はかえす、「届」はとどく。",
    },
    {
        "id": "DRILL-A-138",
        "section": "A",
        "level": "JLPT N4/N5",
        "category": "Kanji Writing (Grafia)",
        "question": "駅の 近くに スーパーが あって とても 【べんり】です。",
        "options": {"A": "便利", "B": "便理", "C": "使利", "D": "便立"},
        "answer": "A",
        "explanation": "「べんり」は「便利」。「理」や「使」との混同に注意。",
    },
    {
        "id": "DRILL-A-139",
        "section": "A",
        "level": "JLPT N4/N5",
        "category": "Kanji Writing (Grafia)",
        "question": "分からない 言葉は 辞書で 【しらべ】ましょう。",
        "options": {"A": "調べ", "B": "課べ", "C": "談べ", "D": "設べ"},
        "answer": "A",
        "explanation": "「しらべる」は「調べる」。言偏の漢字(課・談・設)との判別。",
    },
    {
        "id": "DRILL-A-140",
        "section": "A",
        "level": "JLPT N4/N5",
        "category": "Kanji Writing (Grafia)",
        "question": "道に 落ちて いた ゴミを 【ひろい】ました。",
        "options": {"A": "拾い", "B": "捨て", "C": "持ち", "D": "指し"},
        "answer": "A",
        "explanation": "「ひろう」は「拾う」。「捨てる」(すてる)の対義語。",
    },
]
