#!/usr/bin/env python3
"""
scripts/new_questions_b2.py — 10 New MEXT Part B Questions (DRILL-B-101 to 110).
Strictly <= 200 lines invariant.
"""

QUESTIONS_B2 = [
    {
        "id": "DRILL-B-101",
        "section": "B",
        "level": "JLPT N3/N2",
        "category": "Keigo (敬語)",
        "question": "部長、明日の 役員会議の 配布資料は もう ご覧に（ ）ましたか。",
        "options": {"A": "なり", "B": "いたし", "C": "まいり", "D": "おり"},
        "answer": "A",
        "explanation": "「見る」の尊敬語は「ご覧になる」。「拝見する」は自分の謙譲語。",
    },
    {
        "id": "DRILL-B-102",
        "section": "B",
        "level": "JLPT N3/N2",
        "category": "Keigo (敬語)",
        "question": "先生の 重い お荷物を 私が お持ち（ ）ます。",
        "options": {"A": "し", "B": "になり", "C": "なさり", "D": "下さり"},
        "answer": "A",
        "explanation": "「お〜する」は自分が相手のために行う行為をへりくだる謙譲語I。",
    },
    {
        "id": "DRILL-B-103",
        "section": "B",
        "level": "JLPT N3/N2",
        "category": "Keigo (敬語)",
        "question": "来週の 水曜日、午後二時に 貴社へ（ ）たいと 存じます。",
        "options": {"A": "伺い", "B": "いらっしゃい", "C": "おいでになり", "D": "お越しになり"},
        "answer": "A",
        "explanation": "「行く・訪ねる」の謙譲語は「伺う」。他は尊敬語。",
    },
    {
        "id": "DRILL-B-104",
        "section": "B",
        "level": "JLPT N3/N2",
        "category": "Grammar Connectives",
        "question": "激しい 雨（ ）かかわらず、会場には 多くの 観客が 詰めかけた。",
        "options": {"A": "にも", "B": "へと", "C": "より", "D": "まで"},
        "answer": "A",
        "explanation": "「〜にもかかわらず」は条件に反して事態が生じる逆接表現。",
    },
    {
        "id": "DRILL-B-105",
        "section": "B",
        "level": "JLPT N3/N2",
        "category": "Grammar Connectives",
        "question": "この 専門用語は、初心者（ ）は 少し 理解しにくい。",
        "options": {"A": "にとって", "B": "について", "C": "に対して", "D": "によって"},
        "answer": "A",
        "explanation": "「〜にとって」はその人の立場・視点から見ての評価を表す。",
    },
    {
        "id": "DRILL-B-106",
        "section": "B",
        "level": "JLPT N3/N2",
        "category": "Grammar Connectives",
        "question": "薬を 飲んだ（ ）、急に 激しい 眠気に 襲われた。",
        "options": {"A": "とたんに", "B": "ついでに", "C": "かわりに", "D": "うえに"},
        "answer": "A",
        "explanation": "動詞た形＋「とたんに」は直後に予期せぬ変化が起こることを表す。",
    },
    {
        "id": "DRILL-B-107",
        "section": "B",
        "level": "JLPT N3/N2",
        "category": "Grammar Connectives",
        "question": "彼は 反省する（ ）、かえって 言い訳ばかり 並べ立てた。",
        "options": {"A": "どころか", "B": "ばかりか", "C": "ほどに", "D": "だけに"},
        "answer": "A",
        "explanation": "「〜どころか」は予想される程度から著しくかけ離れた事態を表す。",
    },
    {
        "id": "DRILL-B-108",
        "section": "B",
        "level": "JLPT N3/N2",
        "category": "Sentence Scrambling (★)",
        "question": "健康を 維持するためには、毎日の ＿ ＿ ★ ＿ 大切である。",
        "options": {"A": "バランスに", "B": "気をつける", "C": "食生活の", "D": "ことが"},
        "answer": "B",
        "explanation": "毎日の【食生活の(C)】【バランスに(A)】【★気をつける(B)】【ことが(D)】大切である。",
    },
    {
        "id": "DRILL-B-109",
        "section": "B",
        "level": "JLPT N3/N2",
        "category": "Sentence Scrambling (★)",
        "question": "たとえ 困難であっても、一度 ＿ ＿ ★ ＿ つもりだ。",
        "options": {"A": "決めた", "B": "あきらめない", "C": "目標は", "D": "決して"},
        "answer": "D",
        "explanation": "一度【決めた(A)】【目標は(C)】【決して(D)】【★あきらめない(B)】つもりだ。",
    },
    {
        "id": "DRILL-B-110",
        "section": "B",
        "level": "JLPT N3/N2",
        "category": "Sentence Scrambling (★)",
        "question": "今回の 海外留学を ＿ ＿ ★ ＿ 考えている。",
        "options": {"A": "将来の", "B": "進路について", "C": "真剣に", "D": "きっかけとして"},
        "answer": "C",
        "explanation": "海外留学を【きっかけとして(D)】【将来の(A)】【進路について(B)】【★真剣に(C)】考えている。",
    },
]
